### PR TITLE
Tensorboard documentation

### PR DESCRIPTION
**Pull request by ethantang95**

### CODE REVIEW

**Comment by ethantang95** [comment]
@timzaman @gheinrich for review please

**Comment by gheinrich** [comment]
Hi Ethan I'd like to know if we're going to use `supervisord` to kick off the TensorBoard daemon.

**Comment by TimZaman** [comment]
@gheinrich I guess not.

**Comment by ethantang95** [comment]
Me and Tim talked about it earlier and I think currently we don't want to add more overhead for dependencies for the build team to include more packages. So we decided to just have some instructions for the user about tensorboard and launching it.

**Comment by ethantang95** [comment]
Merged

**Pull request merged**
